### ISSUE TITLE
API Enhancement

### ISSUE THREAD

**Issue by Green-Wolf** [zxsecurity/steamer#4]
Any chance of getting an API added to this so we can link our tools into it? I was hoping to search by email or password and pull out the results. 

Many thanks!

**Comment by Green-Wolf** [comment]
Also a nifty feature to include would to be for steamer to be able to run john or hashcat when not in use and any passwords that are cracked would be added to the databases.

**Comment by ss23** [comment]
I'd be more than happy to have a more featureful API. At the moment you can just hit the search endpoint with format=json and it'll return results in JSON.
If you wanted to send a PR to expand that into specifying the individual fields, that would be fine, and I'd accept the PR.

As for cracking passwords when not in use, it's something I've thought about, but I'd consider slightly out of scope for steamer itself. Instead, I'd probably write another daemon that runs on the same MongoDB instance and cracks them there.

**Comment by Green-Wolf** [comment]
Thats great! Just having the json formatted search should be enough for now. Do you have any plans to work on such a cracking daemon in the near future?

**Comment by bogannz** [comment]
Not at this stage, we have separate workflows for cracking of hashes

**Comment by bogannz** [comment]
Closing issue
